Add CHARTER.md
ossf/wg-supply-chain-integrity pull request #53
Opened 2022-04-27 19:17 UTC by jchestershopify

This pull request introduces `CHARTER.md`, based on the standard template provided by the OpenSSF. The pull request is in response to the request made by the TAC in #49.

At submission, this PR is **not currently in a mergeable state**. To be merged:

1. There needs to be agreement on the list of Maintainers, and
2. The CHARTER.md needs to be adopted on a particular date; ideally with consent from nominated Maintainers signalled by leaving positive reviews on this PR.

Based on [aggregating meeting notes](https://docs.google.com/spreadsheets/d/1I7xX3wkVHnKkqDHUTBbIWym4PejpCHKAvViv1eLDxhU/edit#gid=0), my preliminary suggestion for a Maintainers list is:

- Kim Lewandowski (Chainguard)
- Mike Malone (smallstep)
- Dan Lorenc (Chainguard)
- Ryan Haning (Microsoft)
- Gavin Hindman (Intel)
- Michael Peters (Red Hat)
- Matt Rutkowski (IBM)

These are people whose names appear >= 10 times in the notes as attendees and who are not LF staff. 

However, some have not been active for some time and it may make sense to strike their names and promote others with fewer attendances. For example, it may make sense to promote Santiago Torres-Arias to the list; he has 9 attendances recorded and broadens our list to include academia.

Overall, though, I suggest that no more than 10 names be chosen to ensure easy quorum for the rare occasions when a vote will be required under the charter's rules.

2022-04-27 21:36 UTC, JanZerebecki requested changes

2022-04-28 13:08 UTC, jchestershopify commented on CHARTER.md
> +This Technical Charter sets forth the responsibilities and procedures for technical contribution to, and oversight of, the Supply Chain Integrity open source community, which has been established as
I'll make a similar change -- I think we want to retain "under", not "of".

2022-04-28 13:09 UTC, jchestershopify commented on CHARTER.md
> +- b. Quorum for TSC meetings requires at least fifty percent of all voting members of the TSC to be present. The TSC may continue to meet if quorum is not met but will be prevented from making any de
I don't expect these mechanics to be exercised often, if at all. They're a backstop for rare occasions where consensus can't be reached. Most work is already async with the meetings acting as join points.

2022-04-28 13:10 UTC, jchestershopify commented on CHARTER.md
> +- c. Except as provided in Section 7.c. and 8.a, decisions by vote at a meeting require a majority vote of those in attendance, provided quorum is met. Decisions made by electronic vote without a mee
Two things.

1. The group has no binding power on its members. The TSC can vote for anything it likes and nobody has to take any notice.
2. Clandestine meetings are meetings without notice, that makes them informal and unable to make decisions in any case.

2022-04-28 13:12 UTC, jchestershopify commented on CHARTER.md
> +- c. Except as provided in Section 7.c. and 8.a, decisions by vote at a meeting require a majority vote of those in attendance, provided quorum is met. Decisions made by electronic vote without a mee
Put another way: I don't consider politicking to be worth worrying about. There's no power to be wielded and if things go off the rails, the TAC can intervene.

I should note that I used to be involved in both student and professional politics, so my rules-lawyering paranoia antennae are well-tuned. They're not twitching here.

2022-04-29 10:14 UTC, JanZerebecki commented on CHARTER.md
> +- b. Quorum for TSC meetings requires at least fifty percent of all voting members of the TSC to be present. The TSC may continue to meet if quorum is not met but will be prevented from making any de
I assumed the opposite due to meeting attendance being used to select a Maintainers suggestion. Where does most of the async work happen? I feel like I don't have any insight in how people in this WG work. This repo didn't see any activity during the time the last 5 meetings and 3 month happened. During the same time there is one mail on the mailing list asking for comments on a Google doc named "Digital Artifact Signing Envelope Format Comparison". I suspect much more happened.

2022-04-29 12:54 UTC, jchestershopify commented on CHARTER.md
> +- b. Quorum for TSC meetings requires at least fifty percent of all voting members of the TSC to be present. The TSC may continue to meet if quorum is not met but will be prevented from making any de
The meeting notes show where folks have fanned out and come back in.

Some working groups alternate meeting times to allow for more timezones to participate. If that's a consideration for you, put it on the agenda and I can raise it for you. Or send an email to the mailing list, if you wish to pursue it yourself. But by and large, this is how the WG has been operating and I don't propose to change that in a boilerplate document.

2022-05-02 11:52 UTC, JanZerebecki commented on CHARTER.md
> +- b. Quorum for TSC meetings requires at least fifty percent of all voting members of the TSC to be present. The TSC may continue to meet if quorum is not met but will be prevented from making any de
Your explanation helped me. Please don't offer another meeting time on my account, as I prefer async.

2023-01-06 15:14 UTC, jchestershopify commented
@kimsterv just going through my old issues and see this one is still open. Should it be closed or merged?

2023-05-02 13:35 UTC, melba-lopez commented
closing due to being old/inactive.  If needed in the future, will create a new PR.

2023-05-02 13:35 UTC, closed without merging

2023-05-02 22:37 UTC, david-a-wheeler commented
We need to have *something* we can call charter. Some organizations cannot participate in a working group without a charter. That said, it's fine to create a new PR to do it!